---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
P <- read_csv("../data/MarriagePanel.csv")
M <- read_csv("../data/MarriageFile.csv")
K <- read_csv("../data/KidPanel.csv")

```


# Facts and Moments from the Data

## Life-Cycle Moments

NOTE: we have some "outlier" observations, marriages that start wheb the woman is very young. we want to perhaps restrict our observations.


```{r}
lc_moms <- P %>%
  mutate(AGE_MAR = YMAR-YBIRTH_M) %>%
  filter(AGE_MAR>=18) %>%
  group_by(M_AGE) %>%
  filter(M_AGE>=22,M_AGE<=40) %>%
  summarize(Divorced = mean(DIV),Kids = mean(YBIRTH<=YEAR),FT = mean(M_hrs>1750,na.rm = TRUE),PT = mean(M_hrs>0 & M_hrs<1750,na.rm = TRUE),DivKids = mean(DIV & YBIRTH<=YEAR)) %>%
  pivot_longer(-M_AGE)

lc_moms %>%
  ggplot(aes(x=M_AGE,y=value)) + geom_point() + geom_line() + facet_wrap(. ~ name,scales="free_y")

```

```{r}
lc_moms <- P %>%
  mutate(AGE_MAR = YMAR-YBIRTH_M) %>%
  filter(AGE_MAR>=18) %>%
  group_by(M_AGE,edW) %>%
  filter(M_AGE>=22,M_AGE<=40) %>%
  summarize(Divorced = mean(DIV),Kids = mean(YBIRTH<=YEAR),FT = mean(M_hrs>1750,na.rm = TRUE),PT = mean(M_hrs>0 & M_hrs<1750,na.rm = TRUE),DivKids = mean(DIV & YBIRTH<=YEAR)) %>%
  pivot_longer(-c("M_AGE","edW"))

lc_moms %>%
  ggplot(aes(x=M_AGE,y=value,color=as.factor(edW))) + geom_point() + geom_line() + facet_wrap(. ~ name)

```


